name: Manual Workflow
on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_configuration: [Release, Debug]

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build client only
      run: msbuild Projects/TMProject/TMProject.vcxproj /m /p:Platform=x86 /p:Configuration=${{matrix.build_configuration}}

    - name: Upload client artifact
      uses: actions/upload-artifact@v4
      with:
        name: WYD_NEWDESTINY_STAGE1_${{matrix.build_configuration}}
        path: v769ClientRelease/WYD.exe
